version: '3.8'

services:
  llm:
    container_name: llm-dialog
    build:
      context: ./app
      dockerfile: Dockerfile.llm
    stdin_open: true
    tty: true
    ports:
      - "8008:8008"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
